"""Generate a markdown index for backlog planning files.

The index output is itself a backlog 'reference' document and must follow the
docs/backlog validator conventions (frontmatter + no H1 headings).
"""

from __future__ import annotations

import argparse
from datetime import date
import re
from pathlib import Path

import yaml


FRONTMATTER_RE = re.compile(r"\A---\s*\n(.*?)\n---\s*\n", re.DOTALL)


def parse_frontmatter(text: str) -> dict[str, object]:
    if not text.startswith("---"):
        return {}
    match = FRONTMATTER_RE.match(text)
    if match is None:
        return {}
    raw = yaml.safe_load(match.group(1)) or {}
    return raw if isinstance(raw, dict) else {}


def repo_relative(root: Path, path: Path) -> str:
    return str(path.relative_to(root)).replace("\\", "/")


def dump_frontmatter(frontmatter: dict[str, object]) -> str:
    def yaml_str(value: object) -> str:
        if value is None:
            return '""'
        text = str(value)
        escaped = text.replace('"', '\\"')
        return f'"{escaped}"'

    ordered_keys = [
        "id",
        "title",
        "type",
        "status",
        "priority",
        "created",
        "last_updated",
        "updated",
        "related",
        "labels",
    ]

    lines: list[str] = ["---"]
    for key in ordered_keys:
        if key not in frontmatter:
            continue
        value = frontmatter[key]
        if isinstance(value, list):
            lines.append(f"{key}:")
            for item in value:
                lines.append(f"  - {yaml_str(item)}")
            continue
        lines.append(f"{key}: {yaml_str(value)}")
    lines.append("---")
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description="Index backlog markdown files into a report.")
    parser.add_argument("--root", required=True, help="Backlog root directory")
    parser.add_argument("--out", required=True, help="Output markdown file")
    parser.add_argument(
        "--fail-on-missing",
        action="store_true",
        help="Fail if required keys are missing",
    )
    args = parser.parse_args()

    root = Path(args.root)
    out = Path(args.out)
    task_files = sorted(path for path in root.rglob("*.md"))

    rows: list[str] = []
    missing_errors: list[str] = []

    for task_file in task_files:
        if task_file.resolve() == out.resolve():
            continue

        rel = task_file.relative_to(root)
        if len(rel.parts) == 1 and (
            rel.name == "current.md" or rel.name == "README.md" or rel.name.startswith("README-")
        ):
            continue

        text = task_file.read_text(encoding="utf-8")
        fm = parse_frontmatter(text)

        task_id = str(fm.get("id", "")).strip()
        title = str(fm.get("title", "")).strip()
        item_type = str(fm.get("type", "")).strip()
        status = str(fm.get("status", "")).strip()
        priority = str(fm.get("priority", "")).strip()
        last_updated = str(fm.get("last_updated", "")).strip()

        if args.fail_on_missing:
            if not task_id:
                missing_errors.append(f"{task_file}: missing id")
            if not title:
                missing_errors.append(f"{task_file}: missing title")

        rows.append(
            "| "
            + " | ".join(
                [
                    f"`{task_id}`",
                    item_type,
                    title,
                    status,
                    priority,
                    last_updated,
                    f"`{repo_relative(Path.cwd(), task_file)}`",
                ]
            )
            + " |"
        )

    if missing_errors:
        for err in missing_errors:
            print(err)
        raise SystemExit(1)

    today = date.today().isoformat()
    existing_frontmatter: dict[str, object] = {}
    if out.exists():
        existing_frontmatter = parse_frontmatter(out.read_text(encoding="utf-8"))

    created = str(existing_frontmatter.get("created", "")).strip() or today

    frontmatter: dict[str, object] = {
        "id": existing_frontmatter.get("id", "backlog-index"),
        "title": existing_frontmatter.get("title", "Backlog — index"),
        "type": existing_frontmatter.get("type", "reference"),
        "status": existing_frontmatter.get("status", "active"),
        "priority": existing_frontmatter.get("priority", "medium"),
        "created": created,
        "last_updated": today,
        "updated": today,
        "related": existing_frontmatter.get(
            "related",
            [
                "docs/backlog/README.md",
                "docs/backlog/current.md",
            ],
        ),
        "labels": existing_frontmatter.get("labels", ["autogenerated"]),
    }

    report = [
        dump_frontmatter(frontmatter).rstrip("\n"),
        "",
        "## Syfte",
        "",
        "En autogenererad översikt över planeringsdokument i `docs/backlog/`.",
        "",
        "## Index",
        "",
        "| ID | Typ | Titel | Status | Prioritet | Senast uppdaterad | Fil |",
        "|---|---|---|---|---|---|---|",
        *rows,
        "",
    ]

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(report), encoding="utf-8")
    print(out)


if __name__ == "__main__":
    main()
